import { Car } from '@/types'

export const FEATURED_CARS: Car[] = [
  {
    id: '1',
    name: 'BMW M4 Competition',
    brand: 'BMW',
    model: 'M4',
    year: 2024,
    category: 'sports',
    price_per_day: 8500,
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
      'https://images.unsplash.com/photo-1617531653332-bd46c16f4d68?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
    rating: 4.9,
    review_count: 124,
    seats: 4,
    fuel_type: 'petrol',
    transmission: 'automatic',
    mileage: '12 km/l',
    engine: '3.0L Twin-Turbo Inline-6',
    top_speed: '290 km/h',
    horsepower: '503 HP',
    features: ['Heated Seats', 'Sunroof', 'Harman Kardon Sound', 'M Adaptive Suspension', 'Head-Up Display'],
    location: 'Bandra, Mumbai',
    city: 'Mumbai',
    available: true,
    description: 'Experience the pinnacle of BMW performance with the M4 Competition. A breathtaking blend of raw power and precision engineering.',
    insurance_included: true,
    security_deposit: 50000,
    min_booking_days: 1,
  },
  {
    id: '2',
    name: 'Mercedes-Benz GLE 450',
    brand: 'Mercedes-Benz',
    model: 'GLE',
    year: 2024,
    category: 'luxury',
    price_per_day: 12000,
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
    rating: 4.8,
    review_count: 89,
    seats: 5,
    fuel_type: 'hybrid',
    transmission: 'automatic',
    mileage: '14 km/l',
    engine: '3.0L Inline-6 EQ Boost',
    top_speed: '250 km/h',
    horsepower: '362 HP',
    features: ['Burmester Sound', 'Air Suspension', 'Panoramic Sunroof', 'MBUX Infotainment', 'Night Package'],
    location: 'Connaught Place, Delhi',
    city: 'Delhi',
    available: true,
    description: 'The perfect blend of luxury and versatility. The GLE commands attention while delivering supreme comfort for any journey.',
    insurance_included: true,
    security_deposit: 75000,
    min_booking_days: 2,
  },
  {
    id: '3',
    name: 'Porsche 911 Carrera',
    brand: 'Porsche',
    model: '911',
    year: 2024,
    category: 'sports',
    price_per_day: 15000,
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
    rating: 5.0,
    review_count: 67,
    seats: 4,
    fuel_type: 'petrol',
    transmission: 'automatic',
    mileage: '10 km/l',
    engine: '3.0L Twin-Turbo Flat-6',
    top_speed: '293 km/h',
    horsepower: '385 HP',
    features: ['Sport Chrono Package', 'PASM', 'Bose Surround', 'PCM Navigation', 'LED Matrix Headlights'],
    location: 'Koregaon Park, Pune',
    city: 'Pune',
    available: true,
    description: 'Legendary. Iconic. Timeless. The 911 Carrera defines the sports car experience with unmatched driving dynamics.',
    insurance_included: true,
    security_deposit: 100000,
    min_booking_days: 1,
  },
  {
    id: '4',
    name: 'Audi Q8 Sportback',
    brand: 'Audi',
    model: 'Q8',
    year: 2024,
    category: 'luxury',
    price_per_day: 11000,
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
    rating: 4.7,
    review_count: 98,
    seats: 5,
    fuel_type: 'diesel',
    transmission: 'automatic',
    mileage: '16 km/l',
    engine: '3.0L V6 TDI',
    top_speed: '250 km/h',
    horsepower: '286 HP',
    features: ['Matrix LED', 'Bang & Olufsen Sound', 'Virtual Cockpit', 'Adaptive Air Suspension', 'Night Vision'],
    location: 'Whitefield, Bangalore',
    city: 'Bangalore',
    available: true,
    description: 'The Q8 Sportback redefines SUV luxury with its coupe-like silhouette and Audi\'s finest technology.',
    insurance_included: true,
    security_deposit: 70000,
    min_booking_days: 2,
  },
  {
    id: '5',
    name: 'Range Rover Autobiography',
    brand: 'Land Rover',
    model: 'Range Rover',
    year: 2024,
    category: 'luxury',
    price_per_day: 18000,
    images: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
    rating: 4.9,
    review_count: 54,
    seats: 5,
    fuel_type: 'hybrid',
    transmission: 'automatic',
    mileage: '13 km/l',
    engine: '4.4L V8 MHEV',
    top_speed: '250 km/h',
    horsepower: '530 HP',
    features: ['Meridian Signature Sound', 'Pixel-Laser LED', 'Executive Rear Seats', 'Dynamic Air Suspension', 'Head-Up Display'],
    location: 'Juhu, Mumbai',
    city: 'Mumbai',
    available: true,
    description: 'The ultimate expression of luxury and capability. Range Rover Autobiography sets the benchmark for premium SUVs.',
    insurance_included: true,
    security_deposit: 120000,
    min_booking_days: 2,
  },
  {
    id: '6',
    name: 'Tesla Model S Plaid',
    brand: 'Tesla',
    model: 'Model S',
    year: 2024,
    category: 'electric',
    price_per_day: 9500,
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80',
    rating: 4.8,
    review_count: 112,
    seats: 5,
    fuel_type: 'electric',
    transmission: 'automatic',
    mileage: '600 km range',
    engine: 'Tri-Motor Electric',
    top_speed: '322 km/h',
    horsepower: '1020 HP',
    features: ['Autopilot', '17" Touchscreen', 'Over-the-Air Updates', 'Supercharger Network', 'Glass Roof'],
    location: 'HSR Layout, Bangalore',
    city: 'Bangalore',
    available: true,
    description: 'The fastest production car ever made. Tesla Model S Plaid redefines what\'s possible in an electric vehicle.',
    insurance_included: true,
    security_deposit: 65000,
    min_booking_days: 1,
  },
  {
    id: '7',
    name: 'Lamborghini Huracán EVO',
    brand: 'Lamborghini',
    model: 'Huracán',
    year: 2024,
    category: 'sports',
    price_per_day: 45000,
    images: [
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80',
    rating: 5.0,
    review_count: 31,
    seats: 2,
    fuel_type: 'petrol',
    transmission: 'automatic',
    mileage: '7 km/l',
    engine: '5.2L Naturally Aspirated V10',
    top_speed: '325 km/h',
    horsepower: '640 HP',
    features: ['LDVI System', 'Magneto-Rheological Suspension', 'ALA 2.0', 'Carbon Ceramic Brakes', 'Lamborghini Dynamic Steering'],
    location: 'Pedder Road, Mumbai',
    city: 'Mumbai',
    available: true,
    description: 'A symphony of speed and passion. The Huracán EVO is the purest expression of Lamborghini\'s supercar heritage.',
    insurance_included: true,
    security_deposit: 300000,
    min_booking_days: 1,
  },
  {
    id: '8',
    name: 'Ferrari Roma',
    brand: 'Ferrari',
    model: 'Roma',
    year: 2024,
    category: 'sports',
    price_per_day: 40000,
    images: [
      'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80',
    rating: 4.9,
    review_count: 28,
    seats: 4,
    fuel_type: 'petrol',
    transmission: 'automatic',
    mileage: '8 km/l',
    engine: '3.9L Twin-Turbo V8',
    top_speed: '320 km/h',
    horsepower: '612 HP',
    features: ['Ferrari Dynamic Enhancer', 'Side Slip Control', 'Manettino Dial', 'JBL Professional Sound', 'Carbon Fibre Package'],
    location: 'DLF Phase 5, Gurgaon',
    city: 'Delhi',
    available: true,
    description: 'La Nuova Dolce Vita. The Ferrari Roma captures the spirit of Italian elegance and automotive passion.',
    insurance_included: true,
    security_deposit: 250000,
    min_booking_days: 1,
  },
]

export const LUXURY_BRANDS = [
  { name: 'Lamborghini', logo: '🐂', color: 'from-yellow-500 to-yellow-300' },
  { name: 'Ferrari', logo: '🐴', color: 'from-red-600 to-red-400' },
  { name: 'BMW', logo: '🔵', color: 'from-blue-600 to-blue-400' },
  { name: 'Mercedes', logo: '⭐', color: 'from-gray-600 to-gray-400' },
  { name: 'Audi', logo: '⭕', color: 'from-gray-700 to-gray-500' },
  { name: 'Porsche', logo: '🏇', color: 'from-yellow-600 to-yellow-400' },
  { name: 'Rolls Royce', logo: '👑', color: 'from-purple-600 to-purple-400' },
  { name: 'Range Rover', logo: '🦁', color: 'from-green-700 to-green-500' },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Arjun Mehta',
    city: 'Mumbai',
    rating: 5,
    review: 'CarHub360 completely elevated my business trip experience. The BMW M4 I rented was impeccably maintained and the booking process was seamlessly smooth. This is the future of car rentals.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    role: 'Tech Entrepreneur',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    city: 'Delhi',
    rating: 5,
    review: 'The Porsche 911 on our anniversary road trip was absolutely magical. CarHub360\'s attention to detail and premium service made it an unforgettable journey. Worth every rupee!',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b5bc?w=100&q=80',
    role: 'Fashion Designer',
  },
  {
    id: 3,
    name: 'Vikram Singh',
    city: 'Bangalore',
    rating: 5,
    review: 'As a frequent corporate traveler, I\'ve used many rental services. CarHub360 is simply in a league of its own. The Tesla Model S experience was phenomenal. 10/10 would recommend.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    role: 'Investment Banker',
  },
  {
    id: 4,
    name: 'Sneha Kapoor',
    city: 'Pune',
    rating: 5,
    review: 'Rented the Range Rover for my wedding day and it was absolute perfection. The team at CarHub360 made every detail flawless. My guests were blown away!',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
    role: 'Film Producer',
  },
  {
    id: 5,
    name: 'Rahul Verma',
    city: 'Hyderabad',
    rating: 5,
    review: 'The AI Trip Planner feature saved me hours of research. It perfectly planned my Goa trip with the ideal car, hotels, and budget. This is truly next-generation car rental.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    role: 'Software Architect',
  },
]

export const STATS = [
  { value: 10000, label: 'Happy Customers', suffix: '+', icon: '👥' },
  { value: 2500, label: 'Premium Cars', suffix: '+', icon: '🚗' },
  { value: 100, label: 'Cities Covered', suffix: '+', icon: '🏙️' },
  { value: 4.9, label: 'Average Rating', suffix: '★', icon: '⭐', decimal: true },
]
